FoodTrakker/FoodTrakkerWebAplication/Controllers/LocationController.cs
using FoodTrakker.Core.Model;
using FoodTrakker.Repository.Constants;
using FoodTrakker.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FoodTrakkerWebAplication.Controllers
{
    [Authorize(Roles = Roles.Administrator + "," + Roles.Owner)]
    public class LocationController : Controller
    {
        private readonly LocationService _locationService;
        public LocationController(LocationService locationService)
        {
            _locationService = locationService;
        }

        // GET: LocationController/Create
        public async Task<ActionResult> CreateLocation()
        {

            return View();
        }

        // POST: LocationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateLocation(Location location)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("CreateLocation");
            }

            try
            {

                await _locationService.AddLocation(location);

                return RedirectToAction("CreateFoodTruck", "Owner");
            }
            catch
            {
                return View();
            }
        }



    }
}

FoodTrakker/FoodTrakkerWebAplication/Controllers/OwnerController.cs
using AutoMapper;
using FoodTrakker.Core.LinkingClasses;
using FoodTrakker.Core.Model;
using FoodTrakker.Repository;
using FoodTrakker.Repository.Constants;
using FoodTrakker.Services;
using FoodTrakker.Services.DTOs;
using FoodTrakkerWebAplication.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.TagHelpers.Cache;
using System.Security.Claims;

namespace FoodTrakkerWebAplication.Controllers
{
    [Authorize(Roles = Roles.Administrator + "," + Roles.Owner)]
    public class OwnerController : Controller
    {
        private readonly FoodTruckService _foodTruckService;
        private readonly EventService _eventService;
        private readonly LocationService _locationService;
        private readonly TypeService _typeService;
        private readonly UserManager<User> _userManager;
        private readonly IMapper _mapper;
        private readonly ILogger<OwnerController> _logger;


        public OwnerController(
            EventService eventService,
            FoodTruckService foodTruckService,
            LocationService locationService,
            TypeService typeService,
            UserManager<User> userManager,
            IMapper mapper,
            ILogger<OwnerController> logger)
        {
            _eventService = eventService;
            _foodTruckService = foodTruckService;
            _userManager = userManager;
            _mapper = mapper;
            _locationService = locationService;
            _typeService = typeService;
            _logger = logger;

        }


        // GET: OwnerController
        public async Task<ActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var events = await _eventService.GetOwnerEvents(userId.ToString());
            var foodTrucks = await _foodTruckService.GetOwnerFoodTrucks(userId.ToString());
            var uEViewModel = new FoodTruckEventViewModel();

            uEViewModel.Events = _mapper.Map<List<Event>, List<EventDto>>(events.ToList());
            uEViewModel.Foodtrucks = _mapper.Map<List<FoodTruck>, List<FoodTruckDto>>(foodTrucks.ToList());

            return View(uEViewModel);
        }

        #region FoodTruck

        // GET: OwnerController/Details/5
        public async Task<ActionResult> DetailsFoodTruck(int id)
        {
            var foodTruck = await _foodTruckService.GetFullFoodTruckInfoAsync(id);
            var foodTruckDto = _mapper.Map<FoodTruck, FoodTruckDto>(foodTruck);
            if (foodTruckDto != null)
            {
                return View(foodTruckDto);
            }
            return NotFound();
        }

        // GET: OwnerController/Create
        public async Task<ActionResult> CreateFoodTruck()
        {
            var locations = await _locationService.GetLocationsAsync();
            var locationSelect = new List<SelectListItem>();

            if (locations != null)
            {
                foreach (var location in locations)
                {
                    locationSelect.Add(new SelectListItem { Text = $"{location.City} {location.Street}", Value = $"{location.Id}" });
                }
            }

            ViewBag.LocationSelect = locationSelect;

            var types = await _typeService.GetTypesAsync();
            var typesSelect = new List<SelectListItem>();

            if (types != null)
            {
                foreach (var type in types)
                {
                    typesSelect.Add(new SelectListItem { Text = $"{type.Name}", Value = $"{type.Id}" });
                }
            }

            ViewBag.TypesSelect = typesSelect;


            return View();
        }

        // POST: OwnerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateFoodTruck(FoodTruckDto foodTruckDto, int locationId, int typeId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var foodTruck = _mapper.Map<FoodTruckDto, FoodTruck>(foodTruckDto);
            foodTruck.LocationId = locationId;
            foodTruck.TypeId = typeId;
            foodTruck.OwnerId = userId;

            

            ModelState.Remove("OwnerId");
            ModelState.Remove("Reviews");
            ModelState.Remove("ImageFile");
            ModelState.Remove("ImageName");
            var errors = ModelState.SelectMany(m => m.Value.Errors);
            var isUnique = await _foodTruckService.IsNameUnique(foodTruck.Name);
            if(!isUnique)
                ModelState.AddModelError("Name", "Must be unique!");
            if (!ModelState.IsValid)
            {
                return RedirectToAction("CreateFoodTruck");
            }
            foodTruck.ImageName = _foodTruckService.AddImageToFoodTruck(foodTruck.Name, foodTruckDto.ImageFile);
            try
            {

                await _foodTruckService.AddFoodTruck(foodTruck);
                _logger.LogInformation("Food Truck created");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var locations = await _locationService.GetLocationsAsync();
                var locationSelect = new List<SelectListItem>();

                if (locations != null)
                {
                    foreach (var location in locations)
                    {
                        locationSelect.Add(new SelectListItem { Text = $"{location.City} {location.Street}", Value = $"{location.Id}" });
                    }
                }

                ViewBag.LocationSelect = locationSelect;

                var types = await _typeService.GetTypesAsync();
                var typesSelect = new List<SelectListItem>();

                if (types != null)
                {
                    foreach (var type in types)
                    {
                        typesSelect.Add(new SelectListItem { Text = $"{type.Name}", Value = $"{type.Id}" });
                    }
                }

                ViewBag.TypesSelect = typesSelect;
                return View();
            }
        }

        // GET: OwnerController/Edit/5
        public async Task<ActionResult> EditFoodTruck(int id)
        {


            var foodTruckToEdit = await _foodTruckService.GetFoodTruckAsync(id);
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (foodTruckToEdit.OwnerId != userId)
            {
                return Content("Access denied!");
            }

            var foodTruckToEditDto = _mapper.Map<FoodTruck, FoodTruckDto>(foodTruckToEdit);

            var locations = await _locationService.GetLocationsAsync();
            var locationSelect = new List<SelectListItem>();

            if (locations != null)
            {
                foreach (var location in locations)
                {
                    locationSelect.Add(new SelectListItem { Text = $"{location.City} {location.Street}", Value = $"{location.Id}" });
                }
            }

            ViewBag.LocationSelect = locationSelect;

            var types = await _typeService.GetTypesAsync();
            var typesSelect = new List<SelectListItem>();

            if (types != null)
            {
                foreach (var type in types)
                {
                    typesSelect.Add(new SelectListItem { Text = $"{type.Name}", Value = $"{type.Id}" });
                }
            }

            ViewBag.TypesSelect = typesSelect;

            return View(foodTruckToEditDto);
        }

        // POST: OwnerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditFoodTruck(int id, FoodTruckDto foodTruckDto, int locationId, int typeId)
        {
            ModelState.Remove("OwnerId");
            ModelState.Remove("Reviews");
            ModelState.Remove("ImageFile");
            ModelState.Remove("ImageName");
            if (!ModelState.IsValid)
            {
                return View(foodTruckDto);
            }
            var foodTruckToEdit = await _foodTruckService.GetFoodTruckAsync(id);
            try
            {
                var foodTruck = _mapper.Map<FoodTruckDto, FoodTruck>(foodTruckDto);
                foodTruckToEdit.Name = foodTruck.Name;
                foodTruckToEdit.Description = foodTruck.Description;
                foodTruckToEdit.LocationId = locationId;
                foodTruckToEdit.TypeId = typeId;
                if (foodTruckDto.ImageFile != null)
                {
                    await _foodTruckService.DeleteImageFile(id);
                    foodTruckToEdit.ImageName =  _foodTruckService.AddImageToFoodTruck(foodTruckToEdit.Name, foodTruckDto.ImageFile);
                }
                await _foodTruckService.UpdateFoodTruck(foodTruckToEdit);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OwnerController/Delete/5
        public async Task<ActionResult> DeleteFoodTruck(int id)
        {
            var foodTruckToDelete = await _foodTruckService.GetFoodTruckAsync(id);
            return View(foodTruckToDelete);
        }

        // POST: OwnerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteFoodTruck(int id, FoodTruck foodTruck)
        {
            try
            {
                await _foodTruckService.DeleteImageFile(id);
                await _foodTruckService.DeleteFoodTruck(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        #endregion


        #region Event

FoodTrakker/FoodTrakkerWebAplication/Views/Owner/CreateEvent.cshtml
@model EventDto

@{
	ViewData["Title"] = "CreateFoodTruck";
	Layout = "~/Views/Shared/_Layout.cshtml";
}



@{
	var foodTruck = ViewBag.FoodTruckSelect;
	var types = ViewBag.TypesSelect;
}

<div class="container">
	<h1>Create new event!</h1>
	
	<hr />
	<div class="row">
		<div class="col-md-4">
			<form asp-action="CreateEvent">	
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<partial name="partials/_CreateEditEvent" model="@Model" />
				<h5>Add food trucks!</h5>
				<select asp-for="@Model.FoodTruckEvents " asp-items="@foodTruck" name="foodTruckId" class="form-select"></select>
				<br>
				<div class="form-group">
					<input type="submit" value="Create" class="btn btn-primary" />
				</div>
			</form>
		</div>
	</div>
	<br />
	<div>
		<a asp-action="Index" class="btn btn-light">Back!</a>
	</div>
</div>

FoodTrakker/FoodTrakkerWebAplication/Views/Owner/CreateFoodTruck.cshtml
@model FoodTruckDto

@{
	ViewData["Title"] = "CreateFoodTruck";
	Layout = "~/Views/Shared/_Layout.cshtml";
}



@{
	var location = ViewBag.LocationSelect;
	var types = ViewBag.TypesSelect;
}

<div class="container">
	<h1>Create new Food Truck!</h1>

	<hr />
	<div class="row">
		<div class="col-md-4">
			<form asp-action="CreateFoodTruck" enctype="multipart/form-data">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<h5>Location:</h5>
				<div>
					<select asp-for="@Model.Location" asp-items="@location" name="locationId" class="form-select"></select>
					<a asp-controller="Location" asp-action="CreateLocation" class="btn btn-light">Add new location!</a>
				</div>
				<partial name="partials/_CreateEdit" model="@Model" />
				<h5>Type:</h5>
				<select asp-for="@Model.Type" asp-items="@types" name="typeId" class="form-select"></select>
				<br>
				<br />
				<div class="form-group">
					<input type="submit" value="Create" class="btn btn-primary" />
					<a asp-action="Index" class="btn btn-light">Back!</a>
				</div>
			</form>

		</div>
	</div>
</div>

FoodTrakker/FoodTrakkerWebAplication/Views/Owner/DeleteEvent.cshtml
@model Event

@{
    ViewData["Title"] = "DeleteEvent";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>DeleteEvent</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>
    
    <form asp-action="DeleteEvent">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FoodTrakker/FoodTrakkerWebAplication/Views/Owner/DeleteFoodTruck.cshtml
@model FoodTruck

@{
    ViewData["Title"] = "DeleteFoodTruck";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>DeleteFoodTruck</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FoodTruck</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OwnerId)
        </dd>
    </dl>
    
    <form asp-action="DeleteFoodTruck">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FoodTrakker/FoodTrakkerWebAplication/Views/Owner/DetailsEvent.cshtml
@model EventDto

@{
	ViewData["Title"] = "DetailsEvent";
	Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="container">
	<div class="row">
		<h1>DetailsEvent</h1>
		<h4>Event</h4>
		<hr />
	</div>

	<dl class="row">
		<dt class="col-sm-2">
			<label asp-for="@Model.Name"></label>
		</dt>
		<dd class="col-sm-10">
			@Model.Name
		</dd>
		<dt class="col-sm-2">
			<label asp-for="@Model.Description"></label>
		</dt>
		<dd class="col-sm-10">
			@Model.Description
		</dd>
		<dt class="col-sm-2">
			<label asp-for="@Model.Location"></label>
		</dt>
		<dd class="col-sm-10">
			@Model.Location
		</dd>
		<dt class="col-sm-2">
			<label asp-for="@Model.StartDate"></label>
		</dt>
		<dd class="col-sm-10">
			@Model.StartDate
		</dd>
		<dt class="col-sm-2">
			<label asp-for="@Model.EndDate"></label>
		</dt>
		<dd class="col-sm-10">
			@Model.EndDate
		</dd>
	</dl>
	<a asp-controller="Owner" asp-action="EditEvent" asp-route-id="@Model.Id" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Edit</a>
	<h4>Food Truck present at the event!</h4>
	@await Component.InvokeAsync("EventFoodTrucks", @Model)
	<div>
		<a asp-action="Index" class="btn btn-light">Back to List</a>
	</div>
</div>

FoodTrakker/FoodTrakkerWebAplication/Views/Owner/DetailsFoodTruck.cshtml
@model FoodTruckDto

@{
	ViewData["Title"] = "DetailsFoodTruck";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<br></br>
<br></br>
<div style="margin-left:50px " class="row">
	<div class="col-6">
		<dl class="row">
			<h1>@Model.Name</h1>
			<h5>Food Truck</h5>
			<dt class="col-sm-2">
				<label asp-for="@Model.Name"></label>
			</dt>
			<dd class="col-sm-10">
				@Model.Name
			</dd>
			<dt class="col-sm-2">
				<label asp-for="@Model.Type"></label>
			</dt>
			<dd class="col-sm-10">
				@Model.Type
			</dd>
			<dt class="col-sm-2">
				<label asp-for="@Model.Description"></label>
			</dt>
			<dd class="col-sm-10">
				@Model.Description
			</dd>
			<dt class="col-sm-2">
				<label asp-for="@Model.Location.ZIPCode">Postal Code</label>
			</dt>
			<dd class="col-sm-10">
				@Model.Location.ZIPCode
			</dd>
			<dt class="col-sm-2">
				<label asp-for="@Model.Location.City"></label>
			</dt>
			<dd class="col-sm-10">
				@Model.Location.City
			</dd>
			<dt class="col-sm-2">
				<label asp-for="@Model.Location.Street"></label>
			</dt>
			<dd class="col-sm-10">
				@Model.Location.Street
			</dd>
			<dt class="col-sm-2">
				<label "Navigate"></label>
			</dt>
			@*<dd class="col-sm-10">
				<a href="https://www.google.com/maps/dir/@Model.Location.City%20/@Model.Location.Street%20"</a>Wskazówki Dojazdu
			</dd>*@
		</dl>
		<a asp-controller="Owner" asp-action="EditFoodTruck" asp-route-id="@Model.Id" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Edit</a>
		<br></br>
		<h5>Reviews</h5>
		@await Component.InvokeAsync("FoodTruckReview", @Model.Id)
	</div>
	@*<div class="col-2">
		<img src="~/img/FoodTruckImg/@Model.ImageName" class="card-img-top FTImage" alt="@Model.Name" asp-append-version="true">
	</div>*@

	<div class="col-6">
		<div class="gmap_canvas">
			<iframe width="700" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=@Model.Location.City%20/@Model.Location.Street%20&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="1" scrolling="no" marginheight="1" marginwidth="1">
			</iframe><br>
			<style>
							 .mapouter {
								 position: relative;
								 text-align: right;
								 height: 500px;
								 width: 700px;
								 
								
							 }
							 .gmap_canvas {
								 overflow: hidden;
								 background: none !important;
								 height: 500px;
								 width: 700px;
							 }
			</style>
		</div>
	</div>
</div>

FoodTrakker/FoodTrakkerWebAplication/Views/Owner/EditEvent.cshtml
@model EventDto

@{
	ViewData["Title"] = "EditFoodTruck";
	Layout = "~/Views/Shared/_Layout.cshtml";
}



@{
	var foodTrucks = ViewBag.FoodTruckSelect;
	var foodTrucksToDelete = ViewBag.FoodTruckToDeleteSelect;
}

<div class="container">
	<h1>Edit Food Truck</h1>

	<hr />
	<div class="row">
		<div class="col-md-4">
			<form asp-action="EditEvent">
				<partial name="partials/_CreateEditEvent" model="@Model" />
				<h5>Add new food trucks!</h5>
				<select asp-for="@Model.FoodTruckEvents " asp-items="@foodTrucks" name="foodTruckId" class="form-select"></select>
				<br>
				<h5>Delete food trucks from the list!</h5>
				<select asp-for="@Model.FoodTruckEvents " asp-items="@foodTrucksToDelete" name="foodTruckToDeleteId" class="form-select"></select>
				<br>
				<div class="form-group">
					<input type="submit" value="Save" class="btn btn-primary" />
					<a asp-action="Index" class="btn btn-light">Back to List</a>
				</div>
			</form>
		</div>
	</div>
</div>

FoodTrakker/FoodTrakkerWebAplication/Views/Owner/EditFoodTruck.cshtml
@model FoodTruckDto

@{
	ViewData["Title"] = "EditFoodTruck";
	Layout = "~/Views/Shared/_Layout.cshtml";
}



@{
	var location = ViewBag.LocationSelect;
	var types = ViewBag.TypesSelect;
}

<div class="container">
	<h1>Edit Food Truck</h1>

	<hr />
	<div class="row">
		<div class="col-md-4">
			<form asp-action="EditFoodTruck" enctype="multipart/form-data">
				<partial name="partials/_CreateEdit" model="@Model" />
				<select asp-for="@Model.Type" asp-items="@types" name="typeId" class="form-select"></select>
				<br>
				<select asp-for="@Model.Location" asp-items="@location" name="locationId" class="form-select"></select>
				<a asp-controller="Location" asp-action="CreateLocation" class="btn btn-light">Add new location!</a>
				<br>
				<div class="form-group">
					<input type="submit" value="Save" class="btn btn-primary" />
					<a asp-action="Index" class="btn btn-light">Back to List</a>
				</div>
			</form>
		</div>
	</div>
</div>

FoodTrakker/FoodTrakkerWebAplication/Views/Owner/Index.cshtml
@model FoodTrakkerWebAplication.Models.ViewModel.FoodTruckEventViewModel

@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container">
	<br />
	<div class="row">
		<a asp-controller="Owner" asp-action="CreateFoodTruck" class="btn btn-light"><i class="bi bi-plus-square"></i> Add new food truck!</a>
	</div>
	<h1>Food Trucks</h1>
	<div class="row">
		<partial name="partials/_FoodTruckList" model="Model" />
	</div>
	<br />
	<div class="row">
		<a asp-controller="Owner" asp-action="CreateEvent" class="btn btn-light"><i class="bi bi-plus-square"></i> Add new event!</a>
	</div>
	<h1>Events</h1>
	<div class="row">
		<partial name="partials/_EventsList" model="Model" />
	</div>
</div>


<form id="deleteFoodTruckForm" asp-action="DeleteFoodTruck">
	<input type="hidden" id="foodTruckId" name="Id"/>
</form>

<form id="deleteEventForm" asp-action="DeleteEvent">
	<input type="hidden" id="eventId" name="Id"/>
</form>


@section Scripts{
	<script>
		$(function() {
            $('.deleteFoodTruck').click(function(e) {
                swal({
                    title: "Are You sure?",
                    text: "Are You sure you want to delete this food truck?",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true
                }).then((confirm) => {
                    if (confirm) {
                        var btn = $(this);
                        var id = btn.data("id");
                        $('#foodTruckId').val(id);
                        $('#deleteFoodTruckForm').submit();
					}
				});
            });
		});
				$(function() {
            $('.deleteEvent').click(function(e) {
                swal({
                    title: "Are You sure?",
                    text: "Are You sure you want to delete this event?",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true
                }).then((confirm) => {
                    if (confirm) {
                        var btn = $(this);
                        var id = btn.data("id");
                        $('#eventId').val(id);
                        $('#deleteEventForm').submit();
					}
				});
            });
		});
	</script>
}