FoodTrakker/FoodTrakkerWebAplication/Controllers/EventController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using FoodTrakker.Core.Model;
using FoodTrakker.Repository;
using FoodTrakker.Services;
using AutoMapper;
using FoodTrakker.Services.DTOs;

namespace FoodTrakkerWebAplication.Controllers
{
    public class EventController : Controller
    {
        private readonly EventService _eventService;
        private readonly IMapper _mapper;
        public EventController(EventService eventService, IMapper mapper)
        {
            _eventService = eventService;
            _mapper = mapper;
        }
       
        // GET: EventController
        public async Task<ActionResult> Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var eventsLogged = await _eventService.GetEventsAsync();
                var eventsDto = _mapper.Map<ICollection<Event>, ICollection<EventDto>>(eventsLogged);
                return View(eventsDto);
            }
            var events = await _eventService.GetEventsAsync();
            var eventInNearFuture = events.OrderBy(e => e.StartDate)
                .Where(e => e.StartDate > DateTime.UtcNow)
                .Take(3).ToList();
            var eventDtoInNearFuture = _mapper.Map<List<Event>,List<EventDto>>(eventInNearFuture);
            return View(eventDtoInNearFuture);
        }
       
        // GET: OwnerController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var events = await _eventService.GetFullEventInfoAsync(id);
            var eventsDto = _mapper.Map<Event, EventDto>(events);
            if (eventsDto != null)
            {

                return View(eventsDto);
            }

            return NotFound();
        }

    }
}

FoodTrakker/FoodTrakkerWebAplication/Controllers/FoodTrucksController.cs
using AutoMapper;
using FoodTrakker.Core.Model;
using Microsoft.AspNetCore.Mvc;
using FoodTrakker.Services;
using FoodTrakker.Repository;
using FoodTrakker.Services.DTOs;
using FoodTrakkerWebAplication.Models.ViewModel;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FoodTrakkerWebAplication.Controllers
{
    public class FoodTrucksController : Controller
    {
        private readonly FoodTruckService _foodTruckService;
        private readonly UserService _userService;
        private readonly IMapper _mapper;
        private readonly EventService _eventService;


        public FoodTrucksController(EventService eventService, FoodTruckService foodTruckService, IMapper mapper, UserService userService)
        {
            _foodTruckService = foodTruckService;
            _userService = userService;
            _mapper = mapper;
            _eventService = _eventService;

        }

        public async Task<ActionResult> Index(string EventName, string Type, string searchString, string citySearchString, string streetSearchString, int averageRating)
        {

            var foodTrucks = new List<FoodTruck>();
            if (!String.IsNullOrEmpty(searchString))
            {
                foodTrucks = await _foodTruckService.FindFoodTruckAsync(searchString);
            }
            else if (!String.IsNullOrEmpty(citySearchString))
            {
                foodTrucks = await _foodTruckService.FindByCityAsync(citySearchString);
            }
            else if (!String.IsNullOrEmpty(streetSearchString))
            {
                foodTrucks = await _foodTruckService.FindByStreetAsync(streetSearchString);
            }
            else if (!String.IsNullOrEmpty(Type))
            {
                foodTrucks = await _foodTruckService.FindByTypeAsync(Type);
            }
            else if (!String.IsNullOrEmpty(EventName))
            {
                foodTrucks = await _foodTruckService.FindByEventAsync(EventName);
            }
            else if (averageRating !=0)
            {
                var foodTrucksToFilter = await _foodTruckService.GetFullFoodTruckInfoAsync();
                var foodTrucksDtos = _mapper.Map<List<FoodTruckDto>>(foodTrucksToFilter);
                foreach (var dto in foodTrucksDtos)
                {
                    (dto.AvgRating, dto.ReviewsTotalCount) = await _foodTruckService.AvgRatingCount(dto.Id);
                }
                var foodTruckTypeDtos = new FoodTruckTypeDto { FoodTrucks = foodTrucksDtos.Where(e => e.AvgRating >= averageRating) };
                foodTruckTypeDtos.FoodTruckTypeName = await _foodTruckService.GetFoodTruckTypeNames();

                return View(foodTruckTypeDtos);
            }
            else
            {
                var foodTrucksNotInLocation = new List<FoodTruck>();
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                if (userId != null)
                {
                    foodTrucks = await _foodTruckService.GetFoodTrucksByUserLocation(userId);
                    foodTrucksNotInLocation = await _foodTruckService.GetFoodTruckNotInUserLocation(userId);
                    foreach (var foodTruck in foodTrucksNotInLocation)
                    {
                        foodTrucks.Add(foodTruck);
                    }
                }

                if (userId == null)
                {
                    foodTrucks = await _foodTruckService.GetFullFoodTruckInfoAsync();
                }
            }



            var foodTruckDto = _mapper.Map<ICollection<FoodTruck>,
                ICollection<FoodTruckDto>>(foodTrucks);

            var foodTruckTypeDto = new FoodTruckTypeDto { FoodTrucks = foodTruckDto };
            foodTruckTypeDto.FoodTruckTypeName = await _foodTruckService.GetFoodTruckTypeNames();

            foreach (var ftBto in foodTruckTypeDto.FoodTrucks)
            {
                (ftBto.AvgRating, ftBto.ReviewsTotalCount) = await _foodTruckService.AvgRatingCount(ftBto.Id);
            }

            ViewBag.RatingList = new List<SelectListItem>
            {
                new SelectListItem{Text = "1", Value = "1"},
                new SelectListItem{Text = "2", Value = "2"},
                new SelectListItem{Text = "3", Value = "3"},
                new SelectListItem{Text = "4", Value = "4"},
                new SelectListItem{Text = "5", Value = "5"},
            };

            return View(foodTruckTypeDto);
        }

        //GET: FoodTrucksController/Details/5
        public async Task<ActionResult> Details(int id)
        {

            var foodTruck = await _foodTruckService.GetFullFoodTruckInfoAsync(id);
            var foodTruckDto = _mapper.Map<FoodTruck, FoodTruckDto>(foodTruck);
            if (foodTruckDto == null)
            {
                return NotFound();
            }
            (foodTruckDto.AvgRating, foodTruckDto.ReviewsTotalCount) = await _foodTruckService.AvgRatingCount(id);
            if (User.Identity.IsAuthenticated)
            {
                var x = User.Claims.FirstOrDefault(c => c.Type == @"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier");
                foodTruckDto.IsAddedToFav = await _foodTruckService.IsAddedToFav(id, x.Value);
                foodTruckDto.HasCurrentUserReview = await _foodTruckService.HasFoodTruckReviewFromUser(id, x.Value);
            }

            return View(foodTruckDto);
        }


    }
}

FoodTrakker/FoodTrakkerWebAplication/Controllers/OwnerController.cs
using AutoMapper;
using FoodTrakker.Core.LinkingClasses;
using FoodTrakker.Core.Model;
using FoodTrakker.Repository;
using FoodTrakker.Repository.Constants;
using FoodTrakker.Services;
using FoodTrakker.Services.DTOs;
using FoodTrakkerWebAplication.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.TagHelpers.Cache;
using System.Security.Claims;

namespace FoodTrakkerWebAplication.Controllers
{
    [Authorize(Roles = Roles.Administrator + "," + Roles.Owner)]
    public class OwnerController : Controller
    {
        private readonly FoodTruckService _foodTruckService;
        private readonly EventService _eventService;
        private readonly LocationService _locationService;
        private readonly TypeService _typeService;
        private readonly UserManager<User> _userManager;
        private readonly IMapper _mapper;
        private readonly ILogger<OwnerController> _logger;


        public OwnerController(
            EventService eventService,
            FoodTruckService foodTruckService,
            LocationService locationService,
            TypeService typeService,
            UserManager<User> userManager,
            IMapper mapper,
            ILogger<OwnerController> logger)
        {
            _eventService = eventService;
            _foodTruckService = foodTruckService;
            _userManager = userManager;
            _mapper = mapper;
            _locationService = locationService;
            _typeService = typeService;
            _logger = logger;

        }


        // GET: OwnerController
        public async Task<ActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var events = await _eventService.GetOwnerEvents(userId.ToString());
            var foodTrucks = await _foodTruckService.GetOwnerFoodTrucks(userId.ToString());
            var uEViewModel = new FoodTruckEventViewModel();

            uEViewModel.Events = _mapper.Map<List<Event>, List<EventDto>>(events.ToList());
            uEViewModel.Foodtrucks = _mapper.Map<List<FoodTruck>, List<FoodTruckDto>>(foodTrucks.ToList());

            return View(uEViewModel);
        }

        #region FoodTruck

        // GET: OwnerController/Details/5
        public async Task<ActionResult> DetailsFoodTruck(int id)
        {
            var foodTruck = await _foodTruckService.GetFullFoodTruckInfoAsync(id);
            var foodTruckDto = _mapper.Map<FoodTruck, FoodTruckDto>(foodTruck);
            if (foodTruckDto != null)
            {
                return View(foodTruckDto);
            }
            return NotFound();
        }

        // GET: OwnerController/Create
        public async Task<ActionResult> CreateFoodTruck()
        {
            var locations = await _locationService.GetLocationsAsync();
            var locationSelect = new List<SelectListItem>();

            if (locations != null)
            {
                foreach (var location in locations)
                {
                    locationSelect.Add(new SelectListItem { Text = $"{location.City} {location.Street}", Value = $"{location.Id}" });
                }
            }

            ViewBag.LocationSelect = locationSelect;

            var types = await _typeService.GetTypesAsync();
            var typesSelect = new List<SelectListItem>();

            if (types != null)
            {
                foreach (var type in types)
                {
                    typesSelect.Add(new SelectListItem { Text = $"{type.Name}", Value = $"{type.Id}" });
                }
            }

            ViewBag.TypesSelect = typesSelect;


            return View();
        }

        // POST: OwnerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateFoodTruck(FoodTruckDto foodTruckDto, int locationId, int typeId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var foodTruck = _mapper.Map<FoodTruckDto, FoodTruck>(foodTruckDto);
            foodTruck.LocationId = locationId;
            foodTruck.TypeId = typeId;
            foodTruck.OwnerId = userId;

            

            ModelState.Remove("OwnerId");
            ModelState.Remove("Reviews");
            ModelState.Remove("ImageFile");
            ModelState.Remove("ImageName");
            var errors = ModelState.SelectMany(m => m.Value.Errors);
            var isUnique = await _foodTruckService.IsNameUnique(foodTruck.Name);
            if(!isUnique)
                ModelState.AddModelError("Name", "Must be unique!");
            if (!ModelState.IsValid)
            {
                return RedirectToAction("CreateFoodTruck");
            }
            foodTruck.ImageName = _foodTruckService.AddImageToFoodTruck(foodTruck.Name, foodTruckDto.ImageFile);
            try
            {

                await _foodTruckService.AddFoodTruck(foodTruck);
                _logger.LogInformation("Food Truck created");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var locations = await _locationService.GetLocationsAsync();
                var locationSelect = new List<SelectListItem>();

                if (locations != null)
                {
                    foreach (var location in locations)
                    {
                        locationSelect.Add(new SelectListItem { Text = $"{location.City} {location.Street}", Value = $"{location.Id}" });
                    }
                }

                ViewBag.LocationSelect = locationSelect;

                var types = await _typeService.GetTypesAsync();
                var typesSelect = new List<SelectListItem>();

                if (types != null)
                {
                    foreach (var type in types)
                    {
                        typesSelect.Add(new SelectListItem { Text = $"{type.Name}", Value = $"{type.Id}" });
                    }
                }

                ViewBag.TypesSelect = typesSelect;
                return View();
            }
        }

        // GET: OwnerController/Edit/5
        public async Task<ActionResult> EditFoodTruck(int id)
        {


            var foodTruckToEdit = await _foodTruckService.GetFoodTruckAsync(id);
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (foodTruckToEdit.OwnerId != userId)
            {
                return Content("Access denied!");
            }

            var foodTruckToEditDto = _mapper.Map<FoodTruck, FoodTruckDto>(foodTruckToEdit);

            var locations = await _locationService.GetLocationsAsync();
            var locationSelect = new List<SelectListItem>();

            if (locations != null)
            {
                foreach (var location in locations)
                {
                    locationSelect.Add(new SelectListItem { Text = $"{location.City} {location.Street}", Value = $"{location.Id}" });
                }
            }

            ViewBag.LocationSelect = locationSelect;

            var types = await _typeService.GetTypesAsync();
            var typesSelect = new List<SelectListItem>();

            if (types != null)
            {
                foreach (var type in types)
                {
                    typesSelect.Add(new SelectListItem { Text = $"{type.Name}", Value = $"{type.Id}" });
                }
            }

            ViewBag.TypesSelect = typesSelect;

            return View(foodTruckToEditDto);
        }

        // POST: OwnerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditFoodTruck(int id, FoodTruckDto foodTruckDto, int locationId, int typeId)
        {
            ModelState.Remove("OwnerId");
            ModelState.Remove("Reviews");
            ModelState.Remove("ImageFile");
            ModelState.Remove("ImageName");
            if (!ModelState.IsValid)
            {
                return View(foodTruckDto);
            }
            var foodTruckToEdit = await _foodTruckService.GetFoodTruckAsync(id);
            try
            {
                var foodTruck = _mapper.Map<FoodTruckDto, FoodTruck>(foodTruckDto);
                foodTruckToEdit.Name = foodTruck.Name;
                foodTruckToEdit.Description = foodTruck.Description;
                foodTruckToEdit.LocationId = locationId;
                foodTruckToEdit.TypeId = typeId;
                if (foodTruckDto.ImageFile != null)
                {
                    await _foodTruckService.DeleteImageFile(id);
                    foodTruckToEdit.ImageName =  _foodTruckService.AddImageToFoodTruck(foodTruckToEdit.Name, foodTruckDto.ImageFile);
                }
                await _foodTruckService.UpdateFoodTruck(foodTruckToEdit);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OwnerController/Delete/5
        public async Task<ActionResult> DeleteFoodTruck(int id)
        {
            var foodTruckToDelete = await _foodTruckService.GetFoodTruckAsync(id);
            return View(foodTruckToDelete);
        }

        // POST: OwnerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteFoodTruck(int id, FoodTruck foodTruck)
        {
            try
            {
                await _foodTruckService.DeleteImageFile(id);
                await _foodTruckService.DeleteFoodTruck(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        #endregion


        #region Event

FoodTrakker/FoodTrakkerWebAplication/Views/Shared/_CommentBox.cshtml
<dl class="dl-horizontal">
    <dt>
        Review
    </dt>

    <dd>
        <div class="commentBox">
            @using (Html.BeginForm("CreateReview", "Review", FormMethod.Post, new { onsubmit = "return SubmitComment()" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="col-md-4 control-label">
                            Your rating <span style="font-weight:normal;">(1 start is bad, 5 star is good)</span>
                        </label>
                        <div class="col-md-7">
                            <div onmouseout="CRateSelected()">
                                <span class="starFade" id="Rate1" onclick="CRate(1)" onmouseover="CRateOver(1)" onmouseout="CRateOut(1)"></span><span class="starFade" id="Rate2" onclick="CRate(2)" onmouseover="CRateOver(2)" onmouseout="CRateOut(2)"></span><span class="starFade" id="Rate3" onclick="CRate(3)" onmouseover="CRateOver(3)" onmouseout="CRateOut(3)"></span><span class="starFade" id="Rate4" onclick="CRate(4)" onmouseover="CRateOver(4)" onmouseout="CRateOut(4)"></span><span class="starFade" id="Rate5" onclick="CRate(5)" onmouseover="CRateOver(5)" onmouseout="CRateOut(5)"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <textarea name="Review" id="Review" required rows="5" style="width:100%;" class="form-control"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="hidden" name="FoodTruckId" value="@ViewBag.FoodTruckId" />
                            <input type="hidden" name="Rating" id="Rating" value="0" />
                            <input type="submit" id="btnRegister" name="btnRegister" value="Submit Review" class="btn btn-warning" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </dd>

</dl>
<script>
    function SubmitComment() {
        if ($("#Rating").val() == "0") {
            alert("Please rate this service provider.");
            return false;
        }
        else {
            return true;
        }
    }

    function CRate(r) {
        $("#Rating").val(r);
        for (var i = 1; i <= r; i++) {
            $("#Rate" + i).attr('class', 'starGlow');
        }
        // unselect remaining
        for (var i = r + 1; i <= 5; i++) {
            $("#Rate" + i).attr('class', 'starFade');
        }
    }

    function CRateOver(r) {
        for (var i = 1; i <= r; i++) {
            $("#Rate" + i).attr('class', 'starGlow');
        }
    }

    function CRateOut(r) {
        for (var i = 1; i <= r; i++) {
            $("#Rate" + i).attr('class', 'starFade');
        }
    }

    function CRateSelected() {
        var setRating = $("#Rating").val();
        for (var i = 1; i <= setRating; i++) {
            $("#Rate" + i).attr('class', 'starGlow');
        }
    }
</script>

FoodTrakker/FoodTrakkerWebAplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - FoodTrakkerWebAplication</title>
	<link rel="stylesheet" href="~/css/cerulean.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/searchbar2.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/about.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />


	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
</head>
<body>
	@if (ViewData["Title"] == "Food Trucks")
	{

	}
	else
	{
		<div>
			<partial name="_NavbarPartial" />
		</div>
	}

	<div class="container-fluid">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>
	@if (ViewData["Title"] == "Food Trucks" || ViewData["Title"] == "Log in")
	{	}else
	{
		<footer class="border-top footer text-muted">
			<div class="container">
				<div class="row">
					<div class="col-8">
						&copy; @DateTime.Now.Year - FoodTrakkerWebAplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
					</div>
				</div>
			</div>
		</footer>
	}
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/lib/sweetalert/sweetalert.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FoodTrakker/FoodTrakkerWebAplication/Views/Shared/_NavbarPartial.cshtml
<div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/img/logo.png" class="img-fluid" alt="FoodTrakker!">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item active">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Menu</a>
                        <div class="dropdown-menu">
                            @*<a class="dropdown-item" asp-controller="MergedList" asp-action="Index"><i class="bi bi-card-list"></i> List</a>*@
                            <a class="dropdown-item" asp-controller="FoodTrucks" asp-action="Index"><i class="bi bi-truck"></i> Food Trucks</a>
                                @if (User.Identity.IsAuthenticated)
                                {
                                <a class="dropdown-item" asp-controller="EventLogged" asp-action="Index"><i class="bi bi-calendar2-event"></i> Event</a>
                                }
                                else
                                {
                                <a class="dropdown-item" asp-controller="Event" asp-action="Index"><i class="bi bi-calendar2-event"></i> Event</a>
                                }
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-controller="Home" asp-action="About"><i class="bi bi-cup-hot-fill"></i> About</a>
                        </div>
                    </li>
                </ul>
                <div class="align-items-center">
                    <form class="row row-cols-lg-auto my-lg-0" method="get" asp-controller="Home" asp-action="Index" style="padding-right: 25px;">
                        <div class="col-12" style="padding-right: 0;">
                            <input name="searchString" type="text" class=" d-sm-block d-md-none form-control" placeholder="Search Food Truck..." />
                        </div>
                        <div class="col-12 d-none d-md-none d-lg-block" style="padding-left: 0;">
                        </div>
                    </form>
                </div>
                <div>
                    @if (User.IsInRole(Roles.Administrator) || User.IsInRole(Roles.Owner))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li>
                                <a class="nav-link m-2" asp-area="" asp-controller="Owner" asp-action="Index" style=""><i class="bi bi-speedometer2"></i> Dashboard</a>
                            </li>
                        </ul>
                    }
                </div>
                <div>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </div>
    </nav>
</div>

FoodTrakker/FoodTrakkerWebAplication/Views/Shared/_SearchBlockPartial.cshtml
@using Microsoft.AspNetCore.Identity

@{
	var types = ViewBag.Types;
}

<div>
	<body>
		<form class="row domain-search bg-pblue d-none d-lg-block centerSearch">
			<div class="row">
				<div>
					<h1 style="color:whitesmoke; text-align:center; font-size:64px;">Find your favourite Food Truck!</h1>
					<div>
						<p style="color:whitesmoke; text-align:center; ">Enter a name of a food truck to see where the delicious food is waiting for you</p>
					</div>
					<br>
					</br>
				</div>
				<br>
				</br>
			</div>
			<div style="margin-left:20%; align-content:center; width:60%" class="align-content-lg-center">

				<div style="align-items:center" class="input-group">
					<input style="align-items:center" name="searchString" type="search" class="form-control" placeholder="Search food truck...">
					<span class="input-group-addon"><input type="submit" asp-controller="FoodTrucks" asp-action="Index" value="search" class="btn btn-primary"></span>
				</div>
				<p style="-moz-text-align-last">
					@foreach (var type in types)
					{
						<strong><a asp-controller="FoodTrucks" asp-action="Index" asp-route-Type="@type.Name" class="removeDec">@type.Name</a></strong>
						@* <strong>@type.Name</strong>*@
					}
			</div>
		</form>
	</body>
</div>

FoodTrakker/FoodTrakkerWebAplication/Views/Shared/_SliderPartial.cshtml
@using Microsoft.AspNetCore.Identity
<div class="d-none d-lg-block">
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <a asp-area="Identity" asp-page="/Account/Register"><img src="~/img/sliderregister1.jpg" class="d-block w-100" alt="..."></a>
            </div>
            <div class="carousel-item">
                <img src="~/img/sliderkahuna1.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                 <img src="~/img/sliderwroclaw1.jpg" class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

    <br>
    </br>
</div>